services:
  - type: web
    name: robot-sri-audit-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python -m playwright install chromium"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    autoDeploy: true
