services:
  - type: web
    name: sri-robot-audit-web
    env: python
    plan: free

    buildCommand: |
      # Instala todas las dependencias del proyecto
      pip install --upgrade pip
      pip install -r requirements.txt

      # Crea carpeta persistente para Playwright
      mkdir -p /opt/render/project/.playwright

      # Instala Chromium y dependencias dentro de esa carpeta
      PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/.playwright python -m playwright install --with-deps chromium

    startCommand: |
      # Establece variables antes de iniciar Streamlit
      export PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/.playwright
      export PYPPETEER_HOME=/opt/render/project/.playwright

      # Inicia la app web
      streamlit run aplicacion.py --server.port $PORT --server.address 0.0.0.0

    autoDeploy: true
