services:
  - type: web
    name: sri-robot-audit-web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: |
      streamlit run aplicacion.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
