services:
  - type: web
    name: sri-robot-audit-web
    env: python
    plan: free

    buildCommand: |
      # Instala dependencias y Playwright CLI
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install chromium --with-deps

      # Crea carpeta persistente para navegadores
      mkdir -p /opt/render/project/.playwright
      cp -r /root/.cache/ms-playwright/* /opt/render/project/.playwright/ || true

    startCommand: |
      export PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/.playwright
      export PYPPETEER_HOME=/opt/render/project/.playwright
      streamlit run aplicacion.py --server.port $PORT --server.address 0.0.0.0

    autoDeploy: true
