services:
  - type: web
    name: sri-robot-audit-web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/.playwright
      PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/.playwright python -m playwright install --with-deps chromium
    startCommand: |
      export PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/.playwright
      streamlit run aplicacion.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
