services:
  - type: web
    name: sri-robot-audit-web
    env: python
    plan: free
    buildCommand: "pip install -r requisitos.txt && python -m playwright install chromium"
    startCommand: "streamlit run aplicacion.py --server.port 10000 --server.address 0.0.0.0"
    autoDeploy: true
