services:
  - type: web
    name: sri-robot-audit-web
    env: python
    plan: free

    buildCommand: |
      # Instala dependencias y Playwright
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install-deps
      python -m playwright install chromium

      # Copia navegadores a una carpeta persistente dentro del proyecto
      mkdir -p /opt/render/project/src/.playwright
      cp -r /root/.cache/ms-playwright/* /opt/render/project/src/.playwright/ || true

    startCommand: |
      export PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/src/.playwright
      export PYPPETEER_HOME=/opt/render/project/src/.playwright
      streamlit run aplicacion.py --server.port $PORT --server.address 0.0.0.0

    autoDeploy: true
